"""Core domain models for DataForge AI v2."""

from datetime import datetime
from enum import Enum, IntEnum
from typing import Any

from pydantic import BaseModel, Field

__all__ = [
    "ExecutionPhase",
    "RetryPolicy",
    "FailurePolicy",
    "AgentHistoryEntry",
    "LogEntry",
    # Domain models
    "BusinessDomain",
    "BusinessObjective",
    "BusinessInsight",
    "KPI",
    "KPIMetric",
    "CleaningRule",
    "SchemaInfo",
    "ColumnProfile",
    "DatasetProfile",
    "FileMetadata",
    "ValidationIssue",
    "ValidationReport",
    "Recommendation",
    "InsightEvidence",
    "BusinessGlossaryTerm",
    "FeatureDefinition",
    "BusinessRule",
]


class ExecutionPhase(IntEnum):
    """Execution phases for the analysis workflow.

    Phases provide ordered guarantees while allowing dynamic routing within phases.
    """

    DATA_INTAKE = 1
    DATA_PREPARATION = 2
    DATA_UNDERSTANDING = 3
    DEEP_ANALYSIS = 4
    STATISTICAL_ANALYSIS = 5
    SYNTHESIS = 6
    OUTPUT = 7

    def __str__(self) -> str:
        """Return human-readable phase name."""
        return self.name.replace("_", " ").title()


class FailurePolicy(Enum):
    """Policy for handling agent failures."""

    HALT = "halt"  # Stop the entire workflow
    SKIP = "skip"  # Skip this agent and continue


class RetryPolicy(BaseModel):
    """Retry configuration for an agent.

    Attributes:
        max_retries: Maximum number of retry attempts.
        backoff_strategy: Backoff strategy ("exponential" or "linear").
        initial_backoff: Initial backoff in seconds.
    """

    max_retries: int = Field(default=2, ge=0, le=5, description="Maximum retry attempts")
    backoff_strategy: str = Field(
        default="exponential",
        description="Backoff strategy: 'exponential' or 'linear'",
    )
    initial_backoff: float = Field(
        default=1.0,
        ge=0.1,
        description="Initial backoff in seconds",
    )

    model_config = {"frozen": True}


class AgentHistoryEntry(BaseModel):
    """Entry in the agent execution history.

    Attributes:
        agent_name: Name of the agent that executed.
        timestamp: ISO timestamp of execution.
        duration_seconds: Execution duration in seconds.
        decision: Agent decision (continue, skip, retry, error).
        message: Agent message.
        quality_score: Quality score (0.0-1.0) if available.
        data_keys_produced: List of state keys produced by this agent.
        metadata: Additional metadata.
    """

    agent_name: str = Field(..., description="Name of the agent")
    timestamp: str = Field(..., description="ISO timestamp of execution")
    duration_seconds: float = Field(..., ge=0, description="Execution duration in seconds")
    decision: str = Field(..., description="Agent decision: continue, skip, retry, error")
    message: str = Field(..., description="Agent message")
    quality_score: float | None = Field(
        None, ge=0.0, le=1.0, description="Quality score (0.0-1.0)"
    )
    data_keys_produced: list[str] = Field(
        default_factory=list, description="State keys produced by this agent"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional metadata"
    )

    model_config = {"frozen": True}


# ============================================================================
# DOMAIN MODELS
# ============================================================================


class BusinessDomain(Enum):
    """Business domain enumeration for domain detection.

    Represents the industry or business vertical that the dataset belongs to.
    Used by BusinessDomainDetectionAgent to tailor analysis and KPIs.
    """

    RETAIL = "retail"
    FINANCE = "finance"
    HR = "hr"
    HEALTHCARE = "healthcare"
    MARKETING = "marketing"
    SAAS = "saas"
    REAL_ESTATE = "real_estate"
    EDUCATION = "education"
    LOGISTICS = "logistics"
    GENERAL = "general"

    def get_display_name(self) -> str:
        """Return human-readable display name."""
        return self.value.replace("_", " ").title()


class BusinessObjective(BaseModel):
    """Business objective or question to be answered.

    Represents the business question or objective that the analysis should address.
    Generated by BusinessObjectiveDetectionAgent.
    """

    objective: str = Field(..., description="Business objective or question")
    category: str = Field(
        default="general",
        description="Category: performance, growth, efficiency, risk, etc.",
    )
    priority: str = Field(
        default="medium", description="Priority: low, medium, high, critical"
    )
    confidence: float = Field(
        default=0.5, ge=0.0, le=1.0, description="Confidence in this objective"
    )
    keywords: list[str] = Field(
        default_factory=list, description="Keywords for matching"
    )

    model_config = {"frozen": True}


class BusinessInsight(BaseModel):
    """Business insight derived from data analysis.

    Represents a key finding or insight that addresses a business objective.
    Generated by InsightGenerationAgent.
    """

    category: str = Field(..., description="Insight category")
    title: str = Field(..., description="Insight title")
    summary: str = Field(..., description="Insight summary")
    impact: str = Field(default="medium", description="Business impact: low, medium, high")
    confidence: float = Field(
        default=0.7, ge=0.0, le=1.0, description="Confidence in insight"
    )
    action: str | None = Field(None, description="Recommended action")
    data_sources: list[str] = Field(
        default_factory=list, description="Data columns or metrics used"
    )
    created_at: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="Creation timestamp",
    )

    model_config = {"frozen": True}


class KPIMetric(BaseModel):
    """Individual metric within a KPI.

    Represents a single measurement or calculation that contributes to a KPI.
    """

    name: str = Field(..., description="Metric name")
    value: float | int = Field(..., description="Metric value")
    unit: str | None = Field(None, description="Unit of measurement")
    trend: str = Field(
        default="stable",
        description="Trend: increasing, decreasing, stable",
    )
    benchmark: float | None = Field(
        None, description="Benchmark or target value"
    )
    is_on_track: bool | None = Field(
        None, description="Whether metric is on track with benchmark"
    )

    model_config = {"frozen": True}


class KPI(BaseModel):
    """Key Performance Indicator.

    Represents a business-critical metric that measures performance
    against objectives. Generated by KPIDiscoveryAgent.
    """

    name: str = Field(..., description="KPI name")
    description: str = Field(..., description="KPI description")
    formula: str = Field(..., description="KPI formula or calculation")
    value: float | int | None = Field(None, description="Current KPI value")
    unit: str | None = Field(None, description="Unit of measurement")
    trend: str = Field(
        default="stable", description="Trend: increasing, decreasing, stable"
    )
    benchmark: float | None = Field(None, description="Benchmark or target value")
    is_on_track: bool | None = Field(
        None, description="Whether KPI is on track with benchmark"
    )
    metrics: list[KPIMetric] = Field(
        default_factory=list, description="Component metrics"
    )
    domain: BusinessDomain | None = Field(
        None, description="Business domain this KPI belongs to"
    )
    confidence: float = Field(
        default=0.7, ge=0.0, le=1.0, description="Confidence in KPI"
    )

    model_config = {"frozen": True}


class CleaningRule(BaseModel):
    """Data cleaning rule and its application.

    Represents a cleaning action taken on data, with explanation and impact.
    """

    rule_type: str = Field(
        ..., description="Type: missing_values, duplicates, outliers, etc."
    )
    column: str | None = Field(None, description="Column affected")
    action: str = Field(
        ..., description="Action taken: drop, impute, flag, etc."
    )
    reason: str = Field(..., description="Reason for cleaning action")
    affected_rows: int = Field(
        default=0, ge=0, description="Number of rows affected"
    )
    before_value: str | None = Field(None, description="Value before cleaning")
    after_value: str | None = Field(None, description="Value after cleaning")
    timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="When cleaning was applied",
    )

    model_config = {"frozen": True}


class SchemaInfo(BaseModel):
    """Schema information for a dataset.

    Represents the detected schema including semantic types, keys, and relationships.
    """

    columns: dict[str, dict[str, Any]] = Field(
        ..., description="Column information by name"
    )
    primary_keys: list[str] = Field(
        default_factory=list, description="Detected primary key columns"
    )
    foreign_keys: dict[str, str] = Field(
        default_factory=dict, description="Detected foreign key relationships"
    )
    temporal_columns: list[str] = Field(
        default_factory=list, description="Columns with temporal data"
    )
    hierarchical_columns: list[str] = Field(
        default_factory=list, description="Columns with hierarchical data"
    )
    semantic_types: dict[str, str] = Field(
        default_factory=dict, description="Semantic type per column"
    )
    confidence: float = Field(
        default=0.8, ge=0.0, le=1.0, description="Confidence in schema detection"
    )

    model_config = {"frozen": True}


class ColumnProfile(BaseModel):
    """Profile information for a single column.

    Represents statistical and metadata information about a column.
    """

    name: str = Field(..., description="Column name")
    dtype: str = Field(..., description="Data type")
    non_null_count: int = Field(..., ge=0, description="Number of non-null values")
    null_count: int = Field(..., ge=0, description="Number of null values")
    null_percentage: float = Field(..., ge=0.0, le=100.0)
    unique_count: int | None = Field(None, ge=0, description="Number of unique values")
    unique_percentage: float | None = Field(None, ge=0.0, le=100.0)
    min_value: float | int | str | None = Field(None, description="Minimum value")
    max_value: float | int | str | None = Field(None, description="Maximum value")
    mean: float | None = Field(None, description="Mean value for numeric columns")
    std: float | None = Field(None, description="Standard deviation")
    semantic_type: str | None = Field(None, description="Detected semantic type")
    is_key: bool = Field(default=False, description="Whether column is a key")
    cardinality: str = Field(
        default="medium", description="Cardinality: low, medium, high"
    )

    model_config = {"frozen": True}


class DatasetProfile(BaseModel):
    """Overall profile of the dataset.

    Represents summary statistics and characteristics of the entire dataset.
    """

    row_count: int = Field(..., ge=0, description="Total number of rows")
    column_count: int = Field(..., ge=0, description="Total number of columns")
    memory_usage_mb: float = Field(..., ge=0, description="Memory usage in MB")
    duplicate_rows: int = Field(default=0, ge=0, description="Number of duplicate rows")
    duplicate_percentage: float = Field(
        default=0.0, ge=0.0, le=100.0
    )
    missing_values_total: int = Field(default=0, ge=0, description="Total missing values")
    missing_percentage: float = Field(
        default=0.0, ge=0.0, le=100.0
    )
    numeric_columns: list[str] = Field(default_factory=list)
    categorical_columns: list[str] = Field(default_factory=list)
    temporal_columns: list[str] = Field(default_factory=list)
    text_columns: list[str] = Field(default_factory=list)
    boolean_columns: list[str] = Field(default_factory=list)
    column_profiles: dict[str, ColumnProfile] = Field(
        default_factory=dict, description="Per-column profiles"
    )
    quality_score: float = Field(
        default=1.0, ge=0.0, le=1.0, description="Overall data quality score"
    )
    generated_at: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="When profile was generated",
    )

    model_config = {"frozen": True}


class FileMetadata(BaseModel):
    """Metadata about the input file.

    Represents information about the source file used for analysis.
    """

    filename: str = Field(..., description="Original filename")
    file_path: str = Field(..., description="Full file path")
    file_size_bytes: int = Field(..., ge=0, description="File size in bytes")
    file_size_mb: float = Field(..., ge=0, description="File size in MB")
    file_format: str = Field(..., description="File format: csv, parquet, json, etc.")
    encoding: str = Field(default="utf-8", description="Detected file encoding")
    row_count: int | None = Field(None, ge=0, description="Number of rows")
    column_count: int | None = Field(None, ge=0, description="Number of columns")
    column_names: list[str] = Field(
        default_factory=list, description="List of column names"
    )
    sheet_names: list[str] = Field(
        default_factory=list, description="List of sheet names (Excel only)"
    )
    created_at: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="When metadata was created",
    )
    last_modified: str | None = Field(None, description="File last modified time")

    model_config = {"frozen": True}


class ValidationIssue(BaseModel):
    """Single validation issue found during data validation.

    Represents a specific problem or issue detected during data validation.
    """

    issue_type: str = Field(
        ..., description="Type: missing_data, invalid_format, out_of_range, etc."
    )
    severity: str = Field(
        ..., description="Severity: error, warning, info"
    )
    column: str | None = Field(None, description="Column where issue occurred")
    row_indices: list[int] = Field(
        default_factory=list, description="Row indices where issue occurred"
    )
    message: str = Field(..., description="Issue description")
    suggestion: str | None = Field(None, description="Suggested fix")
    count: int = Field(default=1, ge=1, description="Number of occurrences")

    model_config = {"frozen": True}


class ValidationReport(BaseModel):
    """Complete validation report for a dataset.

    Aggregates all validation issues and provides overall validation status.
    """

    is_valid: bool = Field(..., description="Overall validation status")
    total_issues: int = Field(..., ge=0, description="Total number of issues")
    error_count: int = Field(default=0, ge=0, description="Number of errors")
    warning_count: int = Field(default=0, ge=0, description="Number of warnings")
    info_count: int = Field(default=0, ge=0, description="Number of info messages")
    issues: list[ValidationIssue] = Field(
        default_factory=list, description="List of all issues"
    )
    columns_affected: list[str] = Field(
        default_factory=list, description="Columns with issues"
    )
    recommendations: list[str] = Field(
        default_factory=list, description="Recommendations for fixing issues"
    )
    generated_at: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="When report was generated",
    )

    model_config = {"frozen": True}


class Recommendation(BaseModel):
    """Actionable recommendation based on analysis.

    Represents a specific action or improvement suggested by the analysis.
    """

    category: str = Field(
        ..., description="Category: data_quality, performance, business, etc."
    )
    title: str = Field(..., description="Recommendation title")
    description: str = Field(..., description="Detailed description")
    priority: str = Field(
        default="medium", description="Priority: low, medium, high, critical"
    )
    impact: str = Field(
        default="medium", description="Expected impact: low, medium, high"
    )
    effort: str = Field(
        default="medium", description="Effort required: low, medium, high"
    )
    related_insights: list[str] = Field(
        default_factory=list, description="Insights that led to this recommendation"
    )
    data_columns: list[str] = Field(
        default_factory=list, description="Data columns involved"
    )

    model_config = {"frozen": True}


class InsightEvidence(BaseModel):
    """Evidence supporting a business insight.

    Represents specific data points, statistics, or patterns that support an insight.
    """

    insight_id: str | None = Field(None, description="Related insight ID")
    evidence_type: str = Field(
        ..., description="Type: statistic, pattern, correlation, outlier, etc."
    )
    description: str = Field(..., description="Evidence description")
    data_source: str | None = Field(None, description="Column or metric used")
    value: float | int | str | None = Field(None, description="Evidence value")
    comparison: str = Field(
        default="absolute", description="Comparison type: absolute, relative, benchmark"
    )
    confidence: float = Field(
        default=0.8, ge=0.0, le=1.0, description="Confidence in evidence"
    )
    row_indices: list[int] | None = Field(
        None, description="Row indices supporting this evidence"
    )

    model_config = {"frozen": True}


class BusinessGlossaryTerm(BaseModel):
    """Business glossary term definition.

    Represents a domain-specific term and its definition for context.
    """

    term: str = Field(..., description="Glossary term")
    definition: str = Field(..., description="Term definition")
    domain: BusinessDomain | None = Field(
        None, description="Business domain"
    )
    synonyms: list[str] = Field(
        default_factory=list, description="Synonyms or related terms"
    )
    examples: list[str] = Field(
        default_factory=list, description="Usage examples"
    )
    confidence: float = Field(
        default=0.9, ge=0.0, le=1.0, description="Confidence in definition"
    )

    model_config = {"frozen": True}


class FeatureDefinition(BaseModel):
    """Definition of an engineered feature.

    Represents a feature created by FeatureEngineeringAgent.
    """

    name: str = Field(..., description="Feature name")
    description: str = Field(..., description="Feature description")
    source_columns: list[str] = Field(
        ..., description="Columns used to create this feature"
    )
    transformation: str = Field(
        ..., description="Transformation applied: ratio, bin, extract, etc."
    )
    data_type: str = Field(..., description="Resulting data type")
    example_value: Any = Field(..., description="Example value")
    business_relevance: str = Field(
        default="medium", description="Business relevance: low, medium, high"
    )

    model_config = {"frozen": True}


class BusinessRule(BaseModel):
    """Business rule or constraint.

    Represents a business rule that data should satisfy.
    """

    name: str = Field(..., description="Rule name")
    description: str = Field(..., description="Rule description")
    rule_type: str = Field(
        ..., description="Type: validation, constraint, calculation, etc."
    )
    condition: str | None = Field(
        None, description="Rule condition or expression"
    )
    column: str | None = Field(None, description="Column affected")
    expected_value: Any = Field(None, description="Expected value or range")
    severity: str = Field(
        default="warning", description="Severity: error, warning, info"
    )
    is_active: bool = Field(default=True, description="Whether rule is active")
    domain: BusinessDomain | None = Field(
        None, description="Business domain"
    )

    model_config = {"frozen": True}


class LogEntry(BaseModel):
    """Structured log entry.

    Attributes:
        timestamp: ISO timestamp.
        level: Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL).
        agent: Agent name that generated the log.
        message: Log message.
        metadata: Additional metadata.
    """

    timestamp: str = Field(..., description="ISO timestamp")
    level: str = Field(..., description="Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL")
    agent: str = Field(..., description="Agent name")
    message: str = Field(..., description="Log message")
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional metadata"
    )

    model_config = {"frozen": True}